COUNTRIES = {
    "AFG": {"name": "Afghanistan", "alpha_2": "AF", "alpha_3": "AFG"},
    "ALB": {"name": "Albania", "alpha_2": "AL", "alpha_3": "ALB"},
    "ALG": {"name": "Algeria", "alpha_2": "DZ", "alpha_3": "DZA"},
    "ASA": {"name": "American Samoa", "alpha_2": "AS", "alpha_3": "ASM"},
    "AND": {"name": "Andorra", "alpha_2": "AD", "alpha_3": "AND"},
    "ANG": {"name": "Angola", "alpha_2": "AO", "alpha_3": "AGO"},
    "ANT": {"name": "Antigua and Barbuda", "alpha_2": "AG", "alpha_3": "ATG"},
    "ARG": {"name": "Argentina", "alpha_2": "AR", "alpha_3": "ARG"},
    "ARM": {"name": "Armenia", "alpha_2": "AM", "alpha_3": "ARM"},
    "ARU": {"name": "Aruba", "alpha_2": "AW", "alpha_3": "ABW"},
    "AUS": {"name": "Australia", "alpha_2": "AU", "alpha_3": "AUS"},
    "AUT": {"name": "Austria", "alpha_2": "AT", "alpha_3": "AUT"},
    "AZE": {"name": "Azerbaijan", "alpha_2": "AZ", "alpha_3": "AZE"},
    "BAH": {"name": "Bahamas", "alpha_2": "BS", "alpha_3": "BHS"},
    "BRN": {"name": "Bahrain", "alpha_2": "BH", "alpha_3": "BHR"},
    "BAN": {"name": "Bangladesh", "alpha_2": "BD", "alpha_3": "BGD"},
    "BAR": {"name": "Barbados", "alpha_2": "BB", "alpha_3": "BRB"},
    "BLR": {"name": "Belarus", "alpha_2": "BY", "alpha_3": "BLR"},
    "BEL": {"name": "Belgium", "alpha_2": "BE", "alpha_3": "BEL"},
    "BIZ": {"name": "Belize", "alpha_2": "BZ", "alpha_3": "BLZ"},
    "BEN": {"name": "Benin", "alpha_2": "BJ", "alpha_3": "BEN"},
    "BER": {"name": "Bermuda", "alpha_2": "BM", "alpha_3": "BMU"},
    "BHU": {"name": "Bhutan", "alpha_2": "BT", "alpha_3": "BTN"},
    "BOL": {"name": "Bolivia", "alpha_2": "BO", "alpha_3": "BOL"},
    "BIH": {"name": "Bosnia and Herzegovina", "alpha_2": "BA", "alpha_3": "BIH"},
    "BOT": {"name": "Botswana", "alpha_2": "BW", "alpha_3": "BWA"},
    "BRA": {"name": "Brazil", "alpha_2": "BR", "alpha_3": "BRA"},
    "IVB": {"name": "British Virgin Islands", "alpha_2": "VG", "alpha_3": "VGB"},
    "BRU": {"name": "Brunei Darussalam", "alpha_2": "BN", "alpha_3": "BRN"},
    "BUL": {"name": "Bulgaria", "alpha_2": "BG", "alpha_3": "BGR"},
    "BUR": {"name": "Burkina Faso", "alpha_2": "BF", "alpha_3": "BFA"},
    "BDI": {"name": "Burundi", "alpha_2": "BI", "alpha_3": "BDI"},
    "CAM": {"name": "Cambodia", "alpha_2": "KH", "alpha_3": "KHM"},
    "CMR": {"name": "Cameroon", "alpha_2": "CM", "alpha_3": "CMR"},
    "CAN": {"name": "Canada", "alpha_2": "CA", "alpha_3": "CAN"},
    "CPV": {"name": "Cape Verde", "alpha_2": "CV", "alpha_3": "CPV"},
    "CAY": {"name": "Cayman Islands", "alpha_2": "KY", "alpha_3": "CYM"},
    "CAF": {"name": "Central African Republic", "alpha_2": "CF", "alpha_3": "CAF"},
    "CHA": {"name": "Chad", "alpha_2": "TD", "alpha_3": "TCD"},
    "CHI": {"name": "Chile", "alpha_2": "CL", "alpha_3": "CHL"},
    "CHN": {"name": "China", "alpha_2": "CN", "alpha_3": "CHN"},
    "HKG": {"name": "Hong Kong, SAR China", "alpha_2": "HK", "alpha_3": "HKG"},
    "MAC": {"name": "Macao, SAR China", "alpha_2": "MO", "alpha_3": "MAC"},
    "COL": {"name": "Colombia", "alpha_2": "CO", "alpha_3": "COL"},
    "COM": {"name": "Comoros", "alpha_2": "KM", "alpha_3": "COM"},
    "CGO": {"name": "Congo (Brazzaville)", "alpha_2": "CG", "alpha_3": "COG"},
    "COD": {"name": "Congo (Kinshasa)", "alpha_2": "CD", "alpha_3": "COD"},
    "COK": {"name": "Cook Islands", "alpha_2": "CK", "alpha_3": "COK"},
    "CRC": {"name": "Costa Rica", "alpha_2": "CR", "alpha_3": "CRI"},
    "CIV": {"name": "Cote d'Ivoire", "alpha_2": "CI", "alpha_3": "CIV"},
    "CRO": {"name": "Croatia", "alpha_2": "HR", "alpha_3": "HRV"},
    "CUB": {"name": "Cuba", "alpha_2": "CU", "alpha_3": "CUB"},
    "CYP": {"name": "Cyprus", "alpha_2": "CY", "alpha_3": "CYP"},
    "CZE": {"name": "Czech Republic", "alpha_2": "CZ", "alpha_3": "CZE"},
    "DEN": {"name": "Denmark", "alpha_2": "DK", "alpha_3": "DNK"},
    "DJI": {"name": "Djibouti", "alpha_2": "DJ", "alpha_3": "DJI"},
    "DMA": {"name": "Dominica", "alpha_2": "DM", "alpha_3": "DMA"},
    "ECU": {"name": "Ecuador", "alpha_2": "EC", "alpha_3": "ECU"},
    "EGY": {"name": "Egypt", "alpha_2": "EG", "alpha_3": "EGY"},
    "ESA": {"name": "El Salvador", "alpha_2": "SV", "alpha_3": "SLV"},
    "ERI": {"name": "Eritrea", "alpha_2": "ER", "alpha_3": "ERI"},
    "EST": {"name": "Estonia", "alpha_2": "EE", "alpha_3": "EST"},
    "ETH": {"name": "Ethiopia", "alpha_2": "ET", "alpha_3": "ETH"},
    "FRO": {"name": "Faroe Islands", "alpha_2": "FO", "alpha_3": "FRO"},
    "FIJ": {"name": "Fiji", "alpha_2": "FJ", "alpha_3": "FJI"},
    "FIN": {"name": "Finland", "alpha_2": "FI", "alpha_3": "FIN"},
    "FRA": {"name": "France", "alpha_2": "FR", "alpha_3": "FRA"},
    "GAB": {"name": "Gabon", "alpha_2": "GA", "alpha_3": "GAB"},
    "GAM": {"name": "Gambia", "alpha_2": "GM", "alpha_3": "GMB"},
    "GEO": {"name": "Georgia", "alpha_2": "GE", "alpha_3": "GEO"},
    "GER": {"name": "Germany", "alpha_2": "DE", "alpha_3": "DEU"},
    "GRE": {"name": "Greece", "alpha_2": "GR", "alpha_3": "GRC"},
    "GUM": {"name": "Guam", "alpha_2": "GU", "alpha_3": "GUM"},
    "GUI": {"name": "Guinea", "alpha_2": "GN", "alpha_3": "GIN"},
    "GUY": {"name": "Guyana", "alpha_2": "GY", "alpha_3": "GUY"},
    "HAI": {"name": "Haiti", "alpha_2": "HT", "alpha_3": "HTI"},
    "HON": {"name": "Honduras", "alpha_2": "HN", "alpha_3": "HND"},
    "HUN": {"name": "Hungary", "alpha_2": "HU", "alpha_3": "HUN"},
    "ISL": {"name": "Iceland", "alpha_2": "IS", "alpha_3": "ISL"},
    "IND": {"name": "India", "alpha_2": "IN", "alpha_3": "IND"},
    "INA": {"name": "Indonesia", "alpha_2": "ID", "alpha_3": "IDN"},
    "IRI": {"name": "Iran, Islamic Republic of", "alpha_2": "IR", "alpha_3": "IRN"},
    "IRQ": {"name": "Iraq", "alpha_2": "IQ", "alpha_3": "IRQ"},
    "IRL": {"name": "Ireland", "alpha_2": "IE", "alpha_3": "IRL"},
    "ISR": {"name": "Israel", "alpha_2": "IL", "alpha_3": "ISR"},
    "ITA": {"name": "Italy", "alpha_2": "IT", "alpha_3": "ITA"},
    "JAM": {"name": "Jamaica", "alpha_2": "JM", "alpha_3": "JAM"},
    "JPN": {"name": "Japan", "alpha_2": "JP", "alpha_3": "JPN"},
    "JOR": {"name": "Jordan", "alpha_2": "JO", "alpha_3": "JOR"},
    "KAZ": {"name": "Kazakhstan", "alpha_2": "KZ", "alpha_3": "KAZ"},
    "KEN": {"name": "Kenya", "alpha_2": "KE", "alpha_3": "KEN"},
    "KIR": {"name": "Kiribati", "alpha_2": "KI", "alpha_3": "KIR"},
    "PRK": {"name": "Korea (North)", "alpha_2": "KP", "alpha_3": "PRK"},
    "KOR": {"name": "Korea (South)", "alpha_2": "KR", "alpha_3": "KOR"},
    "KOS": {"name": "Kosovo", "alpha_2": "", "alpha_3": ""},
    "KUW": {"name": "Kuwait", "alpha_2": "KW", "alpha_3": "KWT"},
    "KGZ": {"name": "Kyrgyzstan", "alpha_2": "KG", "alpha_3": "KGZ"},
    "LAO": {"name": "Lao PDR", "alpha_2": "LA", "alpha_3": "LAO"},
    "LAT": {"name": "Latvia", "alpha_2": "LV", "alpha_3": "LVA"},
    "LBN": {"name": "Lebanon", "alpha_2": "LB", "alpha_3": "LBN"},
    "LES": {"name": "Lesotho", "alpha_2": "LS", "alpha_3": "LSO"},
    "LBR": {"name": "Liberia", "alpha_2": "LR", "alpha_3": "LBR"},
    "LBA": {"name": "Libya", "alpha_2": "LY", "alpha_3": "LBY"},
    "LIE": {"name": "Liechtenstein", "alpha_2": "LI", "alpha_3": "LIE"},
    "LTU": {"name": "Lithuania", "alpha_2": "LT", "alpha_3": "LTU"},
    "LUX": {"name": "Luxembourg", "alpha_2": "LU", "alpha_3": "LUX"},
    "MKD": {"name": "Macedonia, Republic of", "alpha_2": "MK", "alpha_3": "MKD"},
    "MAD": {"name": "Madagascar", "alpha_2": "MG", "alpha_3": "MDG"},
    "MAW": {"name": "Malawi", "alpha_2": "MW", "alpha_3": "MWI"},
    "MAS": {"name": "Malaysia", "alpha_2": "MY", "alpha_3": "MYS"},
    "MDV": {"name": "Maldives", "alpha_2": "MV", "alpha_3": "MDV"},
    "MLI": {"name": "Mali", "alpha_2": "ML", "alpha_3": "MLI"},
    "MLT": {"name": "Malta", "alpha_2": "MT", "alpha_3": "MLT"},
    "MHL": {"name": "Marshall Islands", "alpha_2": "MH", "alpha_3": "MHL"},
    "MTN": {"name": "Mauritania", "alpha_2": "MR", "alpha_3": "MRT"},
    "MRI": {"name": "Mauritius", "alpha_2": "MU", "alpha_3": "MUS"},
    "MEX": {"name": "Mexico", "alpha_2": "MX", "alpha_3": "MEX"},
    "FSM": {
        "name": "Micronesia, Federated States of",
        "alpha_2": "FM",
        "alpha_3": "FSM",
    },
    "MDA": {"name": "Moldova", "alpha_2": "MD", "alpha_3": "MDA"},
    "MON": {"name": "Monaco", "alpha_2": "MC", "alpha_3": "MCO"},
    "MGL": {"name": "Mongolia", "alpha_2": "MN", "alpha_3": "MNG"},
    "MNE": {"name": "Montenegro", "alpha_2": "ME", "alpha_3": "MNE"},
    "MAR": {"name": "Morocco", "alpha_2": "MA", "alpha_3": "MAR"},
    "MOZ": {"name": "Mozambique", "alpha_2": "MZ", "alpha_3": "MOZ"},
    "MYA": {"name": "Myanmar", "alpha_2": "MM", "alpha_3": "MMR"},
    "NAM": {"name": "Namibia", "alpha_2": "NA", "alpha_3": "NAM"},
    "NRU": {"name": "Nauru", "alpha_2": "NR", "alpha_3": "NRU"},
    "NEP": {"name": "Nepal", "alpha_2": "NP", "alpha_3": "NPL"},
    "NED": {"name": "Netherlands", "alpha_2": "NL", "alpha_3": "NLD"},
    "AHO": {"name": "Netherlands Antilles", "alpha_2": "AN", "alpha_3": "ANT"},
    "NZL": {"name": "New Zealand", "alpha_2": "NZ", "alpha_3": "NZL"},
    "NCA": {"name": "Nicaragua", "alpha_2": "NI", "alpha_3": "NIC"},
    "NIG": {"name": "Niger", "alpha_2": "NE", "alpha_3": "NER"},
    "NGR": {"name": "Nigeria", "alpha_2": "NG", "alpha_3": "NGA"},
    "NOR": {"name": "Norway", "alpha_2": "NO", "alpha_3": "NOR"},
    "OMA": {"name": "Oman", "alpha_2": "OM", "alpha_3": "OMN"},
    "PAK": {"name": "Pakistan", "alpha_2": "PK", "alpha_3": "PAK"},
    "PLW": {"name": "Palau", "alpha_2": "PW", "alpha_3": "PLW"},
    "PLE": {"name": "Palestinian Territory", "alpha_2": "PS", "alpha_3": "PSE"},
    "PAN": {"name": "Panama", "alpha_2": "PA", "alpha_3": "PAN"},
    "PNG": {"name": "Papua New Guinea", "alpha_2": "PG", "alpha_3": "PNG"},
    "PAR": {"name": "Paraguay", "alpha_2": "PY", "alpha_3": "PRY"},
    "PER": {"name": "Peru", "alpha_2": "PE", "alpha_3": "PER"},
    "PHI": {"name": "Philippines", "alpha_2": "PH", "alpha_3": "PHL"},
    "POL": {"name": "Poland", "alpha_2": "PL", "alpha_3": "POL"},
    "POR": {"name": "Portugal", "alpha_2": "PT", "alpha_3": "PRT"},
    "PUR": {"name": "Puerto Rico", "alpha_2": "PR", "alpha_3": "PRI"},
    "QAT": {"name": "Qatar", "alpha_2": "QA", "alpha_3": "QAT"},
    "ROU": {"name": "Romania", "alpha_2": "RO", "alpha_3": "ROU"},
    "RUS": {"name": "Russian Federation", "alpha_2": "RU", "alpha_3": "RUS"},
    "RWA": {"name": "Rwanda", "alpha_2": "RW", "alpha_3": "RWA"},
    "SKN": {"name": "Saint Kitts and Nevis", "alpha_2": "KN", "alpha_3": "KNA"},
    "LCA": {"name": "Saint Lucia", "alpha_2": "LC", "alpha_3": "LCA"},
    "VIN": {"name": "Saint Vincent and Grenadines", "alpha_2": "VC", "alpha_3": "VCT"},
    "SAM": {"name": "Samoa", "alpha_2": "WS", "alpha_3": "WSM"},
    "SMR": {"name": "San Marino", "alpha_2": "SM", "alpha_3": "SMR"},
    "STP": {"name": "Sao Tome and Principe", "alpha_2": "ST", "alpha_3": "STP"},
    "KSA": {"name": "Saudi Arabia", "alpha_2": "SA", "alpha_3": "SAU"},
    "SEN": {"name": "Senegal", "alpha_2": "SN", "alpha_3": "SEN"},
    "SRB": {"name": "Serbia", "alpha_2": "RS", "alpha_3": "SRB"},
    "SEY": {"name": "Seychelles", "alpha_2": "SC", "alpha_3": "SYC"},
    "SLE": {"name": "Sierra Leone", "alpha_2": "SL", "alpha_3": "SLE"},
    "SGP": {"name": "Singapore", "alpha_2": "SG", "alpha_3": "SGP"},
    "SVK": {"name": "Slovakia", "alpha_2": "SK", "alpha_3": "SVK"},
    "SLO": {"name": "Slovenia", "alpha_2": "SI", "alpha_3": "SVN"},
    "SOL": {"name": "Solomon Islands", "alpha_2": "SB", "alpha_3": "SLB"},
    "SOM": {"name": "Somalia", "alpha_2": "SO", "alpha_3": "SOM"},
    "RSA": {"name": "South Africa", "alpha_2": "ZA", "alpha_3": "ZAF"},
    "SSD": {"name": "South Sudan", "alpha_2": "SS", "alpha_3": "SSD"},
    "ESP": {"name": "Spain", "alpha_2": "ES", "alpha_3": "ESP"},
    "SRI": {"name": "Sri Lanka", "alpha_2": "LK", "alpha_3": "LKA"},
    "SUD": {"name": "Sudan", "alpha_2": "SD", "alpha_3": "SDN"},
    "SUR": {"name": "Suriname", "alpha_2": "SR", "alpha_3": "SUR"},
    "SWZ": {"name": "Swaziland", "alpha_2": "SZ", "alpha_3": "SWZ"},
    "SWE": {"name": "Sweden", "alpha_2": "SE", "alpha_3": "SWE"},
    "SUI": {"name": "Switzerland", "alpha_2": "CH", "alpha_3": "CHE"},
    "SYR": {"name": "Syrian Arab Republic (Syria)", "alpha_2": "SY", "alpha_3": "SYR"},
    "TCH": {"name": "Czechoslovakia", "alpha_2": "CS", "alpha_3": "CSK"},
    "TPE": {"name": "Taiwan, Republic of China", "alpha_2": "TW", "alpha_3": "TWN"},
    "TJK": {"name": "Tajikistan", "alpha_2": "TJ", "alpha_3": "TJK"},
    "TAN": {"name": "Tanzania, United Republic of", "alpha_2": "TZ", "alpha_3": "TZA"},
    "THA": {"name": "Thailand", "alpha_2": "TH", "alpha_3": "THA"},
    "TLS": {"name": "Timor-Leste", "alpha_2": "TL", "alpha_3": "TLS"},
    "TOG": {"name": "Togo", "alpha_2": "TG", "alpha_3": "TGO"},
    "TGA": {"name": "Tonga", "alpha_2": "TO", "alpha_3": "TON"},
    "TTO": {"name": "Trinidad and Tobago", "alpha_2": "TT", "alpha_3": "TTO"},
    "TUN": {"name": "Tunisia", "alpha_2": "TN", "alpha_3": "TUN"},
    "TUR": {"name": "Turkey", "alpha_2": "TR", "alpha_3": "TUR"},
    "TKM": {"name": "Turkmenistan", "alpha_2": "TM", "alpha_3": "TKM"},
    "TUV": {"name": "Tuvalu", "alpha_2": "TV", "alpha_3": "TUV"},
    "UGA": {"name": "Uganda", "alpha_2": "UG", "alpha_3": "UGA"},
    "UKR": {"name": "Ukraine", "alpha_2": "UA", "alpha_3": "UKR"},
    "UAE": {"name": "United Arab Emirates", "alpha_2": "AE", "alpha_3": "ARE"},
    "GBR": {"name": "United Kingdom", "alpha_2": "GB", "alpha_3": "GBR"},
    "USA": {"name": "United States of America", "alpha_2": "US", "alpha_3": "USA"},
    "URS": {"name": "Soviet Union", "alpha_2": "SU", "alpha_3": "SUN"},
    "URU": {"name": "Uruguay", "alpha_2": "UY", "alpha_3": "URY"},
    "UZB": {"name": "Uzbekistan", "alpha_2": "UZ", "alpha_3": "UZB"},
    "VAN": {"name": "Vanuatu", "alpha_2": "VU", "alpha_3": "VUT"},
    "VEN": {
        "name": "Venezuela (Bolivarian Republic)",
        "alpha_2": "VE",
        "alpha_3": "VEN",
    },
    "VIE": {"name": "Viet Nam", "alpha_2": "VN", "alpha_3": "VNM"},
    "ISV": {"name": "Virgin Islands, US", "alpha_2": "VI", "alpha_3": "VIR"},
    "YEM": {"name": "Yemen", "alpha_2": "YE", "alpha_3": "YEM"},
    "YUG": {"name": "Yugoslavia", "alpha_2": "YU", "alpha_3": "YUG"},
    "ZAM": {"name": "Zambia", "alpha_2": "ZM", "alpha_3": "ZMB"},
    "ZIM": {"name": "Zimbabwe", "alpha_2": "ZW", "alpha_3": "ZWE"},
}
